#include "stm32f401xe.h"
#include "pwm.h"

void pwm_init(uint16_t freq, int channel){
	/* CONFIGURING LED FOR TEST */
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	// SET PA5 TO ALTERNATE FXN
	GPIOA->MODER |= (1U << 11);
	GPIOA->MODER &= ~(1U << 10);
	// SET THE FUCNTION TYPE TO TIM2_CH1
	GPIOA->AFR[0] &= ~(0xF << 20);
	GPIOA->AFR[0] |=  (0x1 << 20);   // AF1
	// ------ BS ENDS ------




	/* CONFIGURING THE TIMER CHANNEL 1 */
	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;
	// SET TO OUTPUT COMPARE MODE
	TIM2->CCMR1 &= ~TIM_CCMR1_CC1S;
	// SET THE POLARITY TO ACTIVE HIGH
	TIM2->CCER &= ~TIM_CCER_CC1P;
	// SELECT PWM MODE 1
	TIM2->CCMR1 &= ~TIM_CCMR1_OC1M_Msk;
	TIM2->CCMR1 |= (0x6 << 4);
	// SET PRESCALER
	TIM2->PSC = 0; 			// PRESCALER = 0 + 1
	// SET PWM TIME FREQUENCY
	TIM2->ARR = (16000000 / freq) - 1;
	// ENABLE DUTY CYCLE PRELOAD
	// TO PREVENT GLITCHES IN CURRENT PWM DUTY
	TIM2->CCMR1 |= TIM_CCMR1_OC1PE;
	// ENABLE PERIOD PRELOAD
	// TO PREVENT GLITCHES IN CURRENT PWM PERIOD
	TIM2->CR1 |= TIM_CR1_ARPE;
	// ENABLE EDGE ALIGNED MODE
	// DEFAULT IS UPCOUNTING
	TIM2->CR1 &= ~TIM_CR1_CMS_Msk;
	// ENABLE CAPTURE COMPARE AND COUNTER
	TIM2->CCER |= TIM_CCER_CC1E;
	TIM2->CR1 |= TIM_CR1_CEN;
}

void pwm_set_duty(uint8_t duty){
	if(duty > 100) duty = 100;
	TIM2->CCR1 = (duty * (TIM2->ARR + 1)) / 100;
}
